# Generated by Django 4.2.5 on 2023-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elvis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kind',
            field=models.CharField(default='', max_length=200),
        ),
    ]
