# Generated by Django 4.2.5 on 2023-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elvis', '0004_remove_project_description_alter_about_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
